apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "selfhosted.dev.my.domain/v1",
          "kind": "Selfhostedstage",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "outsystems-operator",
              "app.kubernetes.io/instance": "selfhostedstage-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "selfhostedstage",
              "app.kubernetes.io/part-of": "outsystems-operator"
            },
            "name": "selfhostedstage-sample"
          },
          "spec": {
            "environment": "test-dev"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-06-18T07:05:54Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: outsystems-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Selfhostedstage is the Schema for the selfhostedstages API
      displayName: Selfhostedstage
      kind: Selfhostedstage
      name: selfhostedstages.selfhosted.dev.my.domain
      version: v1
  description: selfhosted operator dev
  displayName: selfhosted
  icon:
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAASsAAACoCAMAAACPKThEAAAA/1BMVEX////vTCM0MjP8/Pw1MzQxLzAuLC38//+RkZEoJicsKiv5+fm0tLQfHB35/////v/x8fFjYmMhISF1c3QmJydAQEClo6Rsamt4eHjb29sAAAAkISPMy8vW1tbExMTt7e2EhIQWFRaAgIBRT1BHRkafn58REBCPj4/l5eWtra3vOQD8//jvSB3sTCW6ubn38OZZV1j1wrD0mH/ve13wYUTwVzTta0vxg2vzq5j01cPoZD7uQQ7zpYv69ej0SCDvq5butKD24tHwcVn2fGn6z8L1PRX2sqbvgmPnYEf86eT4ppPvdlX84dnpUB7nVTb5koDxTjDmjnzgnoXyxa771csmsFfbAAANDElEQVR4nO2cC3ebuBLHMRLIgIVt4kcc/CJ2/ACcuM+0S5smbbN97LZ37939/p/ljniDHds9aW9yzp3f6bY2CGn0ZzQaCbyShCAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgtwLRuqMEeJ58Mdj9fpD2/OYAYFM5hmAxyTGHtqcRw27ePL02fNVpVJ58fLy1Wvjoe15nBBTYl++/ua6vu+DVBX4J3DdZ08M0/QIDsYCzHz9IXAr/ko4VYrvVt68Zab50NY9Lr5cukFl5a8qfl6rytVVsHrnoVvFMAjo7DoIKnfgu99vTIKuJWDEfPvevbpLKqFW8AqHYQhjNy+C1Q6pAPep99BmPjwi+bxZ7XKqWKxLz7x/BkEAqfETqpGkBrl3NT8K80yQyt8nlQ9imfe3TnRyPr5/NZJUvX8tP0zdbLzw/b/2+hWI9RQysHu315vMqve3evFTavlR6uaHOyfAIqvgiXlv11paqnb/Xta43noArdi1uyesp1wFF+y+WjVV+Sdo1dXpQ2j1JdgbqzLH+nBvv/o5Wh3t0OpXhfy6yS4PHIEh7sctWZaY2mIrSf5gephkf4NWtKTVYX0rljpSS1rlGy4YEP+VFiN5g3MXk/12mDfuD0hVCd5vCe6iEWO0JZ8ghQ+RgZtawex/0PRvNLImNrQKq+ktjJxWWZuNfJJiiMZK7eWrvhtzi1vB4vkquPL9yrdtjgXOWKqD1I5Ux3Ho0bmUWtEbz+fLrBfz+bwamQNa6eNFD4jP1Zotx+HT+QA+i+OjXM0j+L4IPw3GFJqQj85JopV+GtZCYl0Gp6KAM+2kvR6CCfBl2LXgwnEkV0+Uspr9vPl9YT2np/19a96LslT+t5Xv+s8uL5/9dnu7WpXDvohYpTrPVa4rAp3TYaJVf6bxo0wrq9WiiVYyVTlwElazmHI1vFg7AaXPTrhDc54xcfhJTXwcO1rUhNMNWziCWnSoxJlF0hpHUEBVZFmxlX48xs5mtk2MpqPK4rDdDw9p8EVWnVODRINRMroOWK/Kin6yL4xebwzB1e3z67eMMdO7eeOXlQQdL+qFxQ4ZO4qs8faUCsWcaixWn8v6caYV9KKdaiWHvQy1GlFd1rX2VOaaBnfe4IrsDNLLFpZMQWIinXLoLZ1SW+PLWCuqKELxSKvGFKTkShtskBWnH9mwtGTbWNsqt7kmU9nuSXNHsTm3QS0+jgOXtNZk1RbW29DwrlBQZy9Lk+BVxf3qsfCiOjNvXrqrq7xr+ZXgujgVjjlV+HwBN2jQtCmddaIGN7RS2tkYPO0NAFHuuEXtYxhljcFxU1h+qsPZdCCfabI+hy99R1Zo35CMRcceJX4V1xLWOtUVbdJvQDVNUFWJxhtoRceW0+0venOHympz6Gjt88Wi1tZlOgvvCJGWnKprMMXoVZXdQdO88P3CKFutgt+zmY6ZxoegFLT8TyzzKyLVoButZPjPLVme9cLO7NIqi+0jW9abSV3isgGHsZVG4rYqqhPZlGwtCobnYzuRqjbVu8m9s2VtHn6qgTWaEwXNvgN+qGpRIWOiymo3urQNo/+QuF73zL/dohT+7dec2zDD9F6Us6+Vl02FhKgK5efppNtMjDhIKyJKaZ34c1TDBOqrxVf1HFldi+NtWVnH7ZE0tmdajSxZmRpJ/IHeR45Vs6hI5aJmxxCooJBog4iKZUccJ40ZVY8iNzbIzhHosTdFt6oEnz1CUr9hrE5elwOae5FLG2pcdCeNxT1bpnxxuFZDXkhMSVJhRFWjFrgFMcAnpjvyqzNL5umkInVs6gwjrUCeRlzxgFOZn8f9lqZJWByBVs34Ru2GsE9Fr1m5TzaK/FFyLPd1TqsjPbUgUcJeHqoVeA70gBZGlwETnNWL+tdWZG6E06FKrU6hPwWt1qqak7LHZTs8dc6Fz8RaGTpolaYjVS0x21IozAVwP/ZIJZnseUmIwCvnmuaTkmO511kRA6ZpO0uIIFRC5Dg6VCvo31qnir7MGzrXIhXAFRw5jvNL4RSneU3zWo1asj7OThEexwFwUfssbQmEb6XtdGCKjALZ2KaKNR/t9ytmropa+e+l0u6nCevFkpxfM61GMOvQfHGQSJkeqpUYtBqcseg80wFiiaKH58YtmUf5A2nacNDqDrdqBcNLnXSbKYqsThKtOukVBa1geNqRoxowKcqadpwlKndAWMmt/KflDSoivS2lo8GbrEjPoZFdCQvIINoHawXV9xRIdyDFPE5v7VoV0Qd8tq1GsouQ3XUUCmnZtC9JSX6VagVBT1Y1O0FTVe1QrYDRBHI6MGDdk3ayoRXosKGVt0OrAWi1zhf/Ya0ko6pzSCxbPHGa83AMibhPk/6AOucTB9JMZRblkAWtIC4p626e5vxgrWDyW1IO+bFykpXdBtviVyU8dlHWMzcGe8mQS8XbNgbJ3VqJScmoTSCrUnh0Y4mhQ9oAXnYMSVUaCsWC71iD4cKjhUF+T2ZY0CTjML8SlQ+7XKHK7HxH0KqbrJw9PTdLfsXq5Y2IfLLaAGnU/G6CmHuakVZxkI/K5dc4m/sM0lBRaJyUEhHdIVUwYPFzVCy1aEKSNAtDW16rXsGFMw7XCm7EFCYZuivF8jYTgotSEcLelGK72GnIW8DzYVE4Qzj3QMBVmulhmKp2aUVg7MKyo5F+hoENYjv9UimpqYQZV1ErqFxpb+nkwVqFoWCqlNsr2Wg+DQrJqB+8Yh6rF4qU0wr3JrfdN26J9VtqqPCfSLuFTWXFSM4MLZqNwTD9jBNwkqgAnZ8lojdh3dGYw2o4rTj5F2JYaxxrlWUea7hhhW6SH9aKQAqr2Evpboh57RYT96vKF7Ow5WJubEQUUrDBDFYL2YQ/12RlEtpKqBwm05HZsHJJtDoWq9501zT1+rlO0w2Goch+2krmfuk+Jgy3SCtYY2unySlYJEOrxa3Pw7QKy0ZZO0wp1k6t2J/lzXb/WTEbvQm+FR+z+i9zbgUrQJidpslid+hkOyJdCACT+BaPYcWfaHXWSqYDkvsbVh2Kk1RDqNiIUvhiI3zA+sWqRR9kmcY6SgYkeVouYsXSHqRVcgWoL+8cg3XJ++4XxFpVgkvP9MRCkMA0ad58LylVTitGLUXW29EGRweWpNY4PtF34MRauFyvaesTJdGqD4Xs6mhxKvrcm/ZDc+tViM/dtNKq2G9Sm+mm3/oskhFmWTnasBrMqGzPR4tqGBz7J5B8ryO3XJw3o+3Ag7Qi7Vp0EAonFt7JvzYe4vifbxhjsIQmjF1XSs/uVyJcFe72AFZUir0+64zbNsSNrMNdDfprT9dtW3eqZ5oS7YsSo61Qquk2F8v7DuftI3EpjF2eJoNkMQOtkoQLgr1tq+tqpwrZu8zPIiEgFEO6bfMoE+44lKq83ew2pxrXVeNQreDO2XK3uqxOoGpnV84g+Gdj57NyFXz6eMEYubn+7JZ33FdX31npEWGvLRIHzdbFJnKyLQp3rDG1KRX7vqozFpFTjae54UwBJWRlBpa3YTWmh5dqdrqAAW/qZvFNKHoCLqpBQi42f+MBNnBUKraDT6Jgea6J9F9VVZHen0RVHaLVKXi/2rJgHlFnnX2Lwo1pLnQt1w38wL31N50ueLf5aKLTnnHLshyrsLyVyJg7lsVnEzC9dmLNksSyTx2r5bQ64QMFy+GWxouXEulMo8myV2wydaZhA3y2zlaEg+nManErfuIhNaqKwzUo41hHw3hYnVgnaSWSwi0n0yo5tZhTMKBlOU5z74qwvrGNsBu/snVML4bLzvlg41RDHI42WEj+odxg2Rkm+cTgfNmp9UuXtuWcEyQNLIfF7QBRSyN79Cf1wjLZsm5jVyr/wJKkp8PL+g1J2rnXJ4VvqX0/+LEz4L7b9vLHxnRd/JZ7qJmVjr5mOX9mKcnvppQaKtZRrGBL4eJBUmgu3ondbvtWCPt48HNnyMT++uUvrIHFI1j32Y/xZfG6dHl7sFjux3u/+7EfY6oq6Z77Y4JI5sWL/S/1xSPw3+VJ8BcwmuhiHf04X3w2X2+kBlv4BsnEZxiBv/hXJ/Vz8QxYGT1OqSTD/N3dH99X34LV21/+85w+JGuQcO7Zo3w4YCnzbv/raqtg9edPeLd2DwNYAWnt3t75++Gos1fityU7hAql+vU/+iJS2+Kn939N+Vdisr9vd7/e536++J/8FuBs3Nv//OkhIcRkNy935Fnf3P9IP+GF7QMsif57zGJJklf33vm3W+fDVcV9/hp/dJmDmObF02Dzlyb+lfvtiVd+ZPF/Td0khskuXq3cfNwSv7b842/PJAS1KsOYd/Pq/cqNCZ5fXpcf7CAx9brHTNP78s8T4OOfF55p1jfeBkEiSF387wZYhHAzz8NfOiMIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiAIgiDb+S/IfiHVzDt6PgAAAABJRU5ErkJggg=="
    mediatype: "image/png"
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - selfhosted.dev.my.domain
          resources:
          - selfhostedstages
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - selfhosted.dev.my.domain
          resources:
          - selfhostedstages/finalizers
          verbs:
          - update
        - apiGroups:
          - selfhosted.dev.my.domain
          resources:
          - selfhostedstages/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: outsystems-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: outsystems-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: outsystems-operator
          control-plane: controller-manager
        name: outsystems-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: public.ecr.aws/w0o4m8y0/selfhosted-os-operator:1.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: outsystems-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: outsystems-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - selfhosted
  links:
  - name: Outsystems Operator
    url: https://outsystems-operator.domain
  maintainers:
  - email: pradip.babar@outsystems.com
    name: pradip
  maturity: alpha
  provider:
    name: outsystems
  version: 0.0.1
