---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selfhosted.dev.my.domain
  resources:
  - selfhostedstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selfhosted.dev.my.domain
  resources:
  - selfhostedstages/finalizers
  verbs:
  - update
- apiGroups:
  - selfhosted.dev.my.domain
  resources:
  - selfhostedstages/status
  verbs:
  - get
  - patch
  - update
