# permissions for end users to edit selfhostedstages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: selfhostedstage-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: outsystems-operator
    app.kubernetes.io/part-of: outsystems-operator
    app.kubernetes.io/managed-by: kustomize
  name: selfhostedstage-editor-role
rules:
- apiGroups:
  - selfhosted.dev.my.domain
  resources:
  - selfhostedstages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - selfhosted.dev.my.domain
  resources:
  - selfhostedstages/status
  verbs:
  - get
